
/* /usr/include/openssl/ssl.h (and friends) */

enum bio_ctrl_cmd { BIO_CTRL_RESET=1, BIO_CTRL_EOF=2, BIO_CTRL_INFO=3, BIO_CTRL_SET=4, BIO_CTRL_GET=5, BIO_CTRL_PUSH=6, BIO_CTRL_POP=7, BIO_CTRL_GET_CLOSE=8, BIO_CTRL_SET_CLOSE=9, BIO_CTRL_PENDING=10, BIO_CTRL_FLUSH=11, BIO_CTRL_DUP=12, BIO_CTRL_WPENDING=13, BIO_CTRL_SET_CALLBACK=14, BIO_CTRL_GET_CALLBACK=15, BIO_CTRL_SET_FILENAME=30, BIO_CTRL_DGRAM_CONNECT=31, BIO_CTRL_DGRAM_SET_CONNECTED=32, BIO_CTRL_DGRAM_SET_RECV_TIMEOUT=33, BIO_CTRL_DGRAM_GET_RECV_TIMEOUT=34, BIO_CTRL_DGRAM_SET_SEND_TIMEOUT=35, BIO_CTRL_DGRAM_GET_SEND_TIMEOUT=36, BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP=37, BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP=38, BIO_CTRL_DGRAM_MTU_DISCOVER=39, BIO_CTRL_DGRAM_QUERY_MTU=40, BIO_CTRL_DGRAM_GET_FALLBACK_MTU=47, BIO_CTRL_DGRAM_GET_MTU=41, BIO_CTRL_DGRAM_SET_MTU=42, BIO_CTRL_DGRAM_MTU_EXCEEDED=43, BIO_CTRL_DGRAM_GET_PEER=46, BIO_CTRL_DGRAM_SET_PEER=44, BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT=45, BIO_CTRL_DGRAM_SET_DONT_FRAG=48, BIO_CTRL_DGRAM_GET_MTU_OVERHEAD=49, BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE=50, BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY=51, BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY=52, BIO_CTRL_DGRAM_SCTP_AUTH_CCS_RCVD=53, BIO_CTRL_DGRAM_SCTP_GET_SNDINFO=60, BIO_CTRL_DGRAM_SCTP_SET_SNDINFO=61, BIO_CTRL_DGRAM_SCTP_GET_RCVINFO=62, BIO_CTRL_DGRAM_SCTP_SET_RCVINFO=63, BIO_CTRL_DGRAM_SCTP_GET_PRINFO=64, BIO_CTRL_DGRAM_SCTP_SET_PRINFO=65, BIO_CTRL_DGRAM_SCTP_SAVE_SHUTDOWN=70, BIO_C_SET_CONNECT=100, BIO_C_DO_STATE_MACHINE=101, BIO_C_SET_NBIO=102, BIO_C_SET_PROXY_PARAM=103, BIO_C_SET_FD=104, BIO_C_GET_FD=105, BIO_C_SET_FILE_PTR=106, BIO_C_GET_FILE_PTR=107, BIO_C_SET_FILENAME=108, BIO_C_SET_SSL=109, BIO_C_GET_SSL=110, BIO_C_SET_MD=111, BIO_C_GET_MD=112, BIO_C_GET_CIPHER_STATUS=113, BIO_C_SET_BUF_MEM=114, BIO_C_GET_BUF_MEM_PTR=115, BIO_C_GET_BUFF_NUM_LINES=116, BIO_C_SET_BUFF_SIZE=117, BIO_C_SET_ACCEPT=118, BIO_C_SSL_MODE=119, BIO_C_GET_MD_CTX=120, BIO_C_GET_PROXY_PARAM=121, BIO_C_SET_BUFF_READ_DATA=122, BIO_C_GET_CONNECT=123, BIO_C_GET_ACCEPT=124, BIO_C_SET_SSL_RENEGOTIATE_BYTES=125, BIO_C_GET_SSL_NUM_RENEGOTIATES=126, BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT=127, BIO_C_FILE_SEEK=128, BIO_C_GET_CIPHER_CTX=129, BIO_C_SET_BUF_MEM_EOF_RETURN=130, BIO_C_SET_BIND_MODE=131, BIO_C_GET_BIND_MODE=132, BIO_C_FILE_TELL=133, BIO_C_GET_SOCKS=134, BIO_C_SET_SOCKS=135, BIO_C_SET_WRITE_BUF_SIZE=136, BIO_C_GET_WRITE_BUF_SIZE=137, BIO_C_MAKE_BIO_PAIR=138, BIO_C_DESTROY_BIO_PAIR=139, BIO_C_GET_WRITE_GUARANTEE=140, BIO_C_GET_READ_REQUEST=141, BIO_C_SHUTDOWN_WR=142, BIO_C_NREAD0=143, BIO_C_NREAD=144, BIO_C_NWRITE0=145, BIO_C_NWRITE=146, BIO_C_RESET_READ_REQUEST=147, BIO_C_SET_MD_CTX=148, BIO_C_SET_PREFIX=149, BIO_C_GET_PREFIX=150, BIO_C_SET_SUFFIX=151, BIO_C_GET_SUFFIX=152, BIO_C_SET_EX_ARG=153, BIO_C_GET_EX_ARG=154 };

enum bio_type { BIO_TYPE_NONE=0, BIO_TYPE_MEM=0x401, BIO_TYPE_FILE=0x402, BIO_TYPE_FD=0x504, BIO_TYPE_SOCKET=0x505, BIO_TYPE_NULL=0x406, BIO_TYPE_SSL=0x207, BIO_TYPE_MD=0x208, BIO_TYPE_BUFFER=0x209, BIO_TYPE_CIPHER=0x20a, BIO_TYPE_BASE64=0x20b, BIO_TYPE_CONNECT=0x50c, BIO_TYPE_ACCEPT=0x50d, BIO_TYPE_PROXY_CLIENT=0x20e, BIO_TYPE_PROXY_SERVER=0x20f, BIO_TYPE_NBIO_TEST=0x210, BIO_TYPE_NULL_FILTER=0x211, BIO_TYPE_BER=0x212, BIO_TYPE_BIO=0x413, BIO_TYPE_LINEBUFFER=0x214, BIO_TYPE_DGRAM=0x515, BIO_TYPE_DGRAM_SCTP=0x518, BIO_TYPE_ASN1=0x216, BIO_TYPE_COMP=0x217, BIO_TYPE_DESCRIPTOR=0x0100, BIO_TYPE_FILTER=0x0200, BIO_TYPE_SOURCE_SINK=0x0400 };

enum openssl_ctrl_cmd { SSL_CTRL_NEED_TMP_RSA=1, SSL_CTRL_SET_TMP_RSA=2, SSL_CTRL_SET_TMP_DH=3, SSL_CTRL_SET_TMP_ECDH=4, SSL_CTRL_SET_TMP_RSA_CB=5, SSL_CTRL_SET_TMP_DH_CB=6, SSL_CTRL_SET_TMP_ECDH_CB=7, SSL_CTRL_GET_SESSION_REUSED=8, SSL_CTRL_GET_CLIENT_CERT_REQUEST=9, SSL_CTRL_GET_NUM_RENEGOTIATIONS=10, SSL_CTRL_CLEAR_NUM_RENEGOTIATIONS=11, SSL_CTRL_GET_TOTAL_RENEGOTIATIONS=12, SSL_CTRL_GET_FLAGS=13, SSL_CTRL_EXTRA_CHAIN_CERT=14, SSL_CTRL_SET_MSG_CALLBACK=15, SSL_CTRL_SET_MSG_CALLBACK_ARG=16, SSL_CTRL_SET_MTU=17, SSL_CTRL_SESS_NUMBER=20, SSL_CTRL_SESS_CONNECT=21, SSL_CTRL_SESS_CONNECT_GOOD=22, SSL_CTRL_SESS_CONNECT_RENEGOTIATE=23, SSL_CTRL_SESS_ACCEPT=24, SSL_CTRL_SESS_ACCEPT_GOOD=25, SSL_CTRL_SESS_ACCEPT_RENEGOTIATE=26, SSL_CTRL_SESS_HIT=27, SSL_CTRL_SESS_CB_HIT=28, SSL_CTRL_SESS_MISSES=29, SSL_CTRL_SESS_TIMEOUTS=30, SSL_CTRL_SESS_CACHE_FULL=31, SSL_CTRL_OPTIONS=32, SSL_CTRL_MODE=33, SSL_CTRL_GET_READ_AHEAD=40, SSL_CTRL_SET_READ_AHEAD=41, SSL_CTRL_SET_SESS_CACHE_SIZE=42, SSL_CTRL_GET_SESS_CACHE_SIZE=43, SSL_CTRL_SET_SESS_CACHE_MODE=44, SSL_CTRL_GET_SESS_CACHE_MODE=45, SSL_CTRL_GET_MAX_CERT_LIST=50, SSL_CTRL_SET_MAX_CERT_LIST=51, SSL_CTRL_SET_MAX_SEND_FRAGMENT=52, SSL_CTRL_SET_TLSEXT_SERVERNAME_CB=53, SSL_CTRL_SET_TLSEXT_SERVERNAME_ARG=54, SSL_CTRL_SET_TLSEXT_HOSTNAME=55, SSL_CTRL_SET_TLSEXT_DEBUG_CB=56, SSL_CTRL_SET_TLSEXT_DEBUG_ARG=57, SSL_CTRL_GET_TLSEXT_TICKET_KEYS=58, SSL_CTRL_SET_TLSEXT_TICKET_KEYS=59, SSL_CTRL_SET_TLSEXT_OPAQUE_PRF_INPUT=60, SSL_CTRL_SET_TLSEXT_OPAQUE_PRF_INPUT_CB=61, SSL_CTRL_SET_TLSEXT_OPAQUE_PRF_INPUT_CB_ARG=62, SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB=63, SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB_ARG=64, SSL_CTRL_SET_TLSEXT_STATUS_REQ_TYPE=65, SSL_CTRL_GET_TLSEXT_STATUS_REQ_EXTS=66, SSL_CTRL_SET_TLSEXT_STATUS_REQ_EXTS=67, SSL_CTRL_GET_TLSEXT_STATUS_REQ_IDS=68, SSL_CTRL_SET_TLSEXT_STATUS_REQ_IDS=69, SSL_CTRL_GET_TLSEXT_STATUS_REQ_OCSP_RESP=70, SSL_CTRL_SET_TLSEXT_STATUS_REQ_OCSP_RESP=71, SSL_CTRL_SET_TLSEXT_TICKET_KEY_CB=72, SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB=75, SSL_CTRL_SET_SRP_VERIFY_PARAM_CB=76, SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB=77, SSL_CTRL_SET_SRP_ARG=78, SSL_CTRL_SET_TLS_EXT_SRP_USERNAME=79, SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH=80, SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD=81, SSL_CTRL_TLS_EXT_SEND_HEARTBEAT=85, SSL_CTRL_GET_TLS_EXT_HEARTBEAT_PENDING=86, SSL_CTRL_SET_TLS_EXT_HEARTBEAT_NO_REQUESTS=87, SSL_CTRL_GET_RI_SUPPORT=76, SSL_CTRL_CLEAR_OPTIONS=77, SSL_CTRL_CLEAR_MODE=78, SSL_CTRL_GET_EXTRA_CHAIN_CERTS=82, SSL_CTRL_CLEAR_EXTRA_CHAIN_CERTS=83, SSL_CTRL_CHAIN=88, SSL_CTRL_CHAIN_CERT=89, SSL_CTRL_GET_CURVES=90, SSL_CTRL_SET_CURVES=91, SSL_CTRL_SET_CURVES_LIST=92, SSL_CTRL_GET_SHARED_CURVE=93, SSL_CTRL_SET_ECDH_AUTO=94, SSL_CTRL_SET_SIGALGS=97, SSL_CTRL_SET_SIGALGS_LIST=98, SSL_CTRL_CERT_FLAGS=99, SSL_CTRL_CLEAR_CERT_FLAGS=100, SSL_CTRL_SET_CLIENT_SIGALGS=101, SSL_CTRL_SET_CLIENT_SIGALGS_LIST=102, SSL_CTRL_GET_CLIENT_CERT_TYPES=103, SSL_CTRL_SET_CLIENT_CERT_TYPES=104, SSL_CTRL_BUILD_CERT_CHAIN=105, SSL_CTRL_SET_VERIFY_CERT_STORE=106, SSL_CTRL_SET_CHAIN_CERT_STORE=107, SSL_CTRL_GET_PEER_SIGNATURE_NID=108, SSL_CTRL_GET_SERVER_TMP_KEY=109, SSL_CTRL_GET_RAW_CIPHERLIST=110, SSL_CTRL_GET_EC_POINT_FORMATS=111, SSL_CTRL_GET_CHAIN_CERTS=115, SSL_CTRL_SELECT_CURRENT_CERT=116, SSL_CTRL_SET_CURRENT_CERT=117, SSL_CTRL_CHECK_PROTO_VERSION=119 };

int SSL_library_init(void);
int SSL_CTX_set_cipher_list(void *ctx, const char *str);
int SSL_set_cipher_list(void *ssl, const char *str);
int SSL_accept(void *ssl);
int SSL_connect(void *ssl);
void *SSL_new(void *ctx);
void SSL_CTX_free(void *ctx);
void *SSL_CTX_new(void *method);
void SSL_CTX_set_verify(void *ctx, int mode, void *verify_cb);
void SSL_CTX_set_verify_depth(void *ctx, int depth);
int SSL_CTX_load_verify_locations(void *ctx, const char *CAfile, const char *CApath);
long SSL_CTX_ctrl(void *ctx, int cmd = openssl_ctrl_cmd, long larg, void *parg);
int SSL_CTX_set_default_verify_paths(void *ctx);
void *SSL_SESSION_new(void);
void SSL_SESSION_free(void *session);
void OPENSSL_cleanse(void *ptr, size_t len);
void OPENSSL_config(const char *config_name);
void OPENSSL_no_config(void);
int SSL_version(void *s);
int SSL_CTX_check_private_key(void *ctx);
int SSL_check_private_key(void *ssl);
void CRYPTO_lock(int mode, int n, const char *file, int line);
int SSL_read(void *ssl, void *buf, int num);
int SSL_write(void *ssl, void *buf, int num);
int SSL_get_fd(void *ssl);
int SSL_get_rfd(void *ssl);
int SSL_get_wfd(void *ssl);
void CRYPTO_free(void *ptr);
void *CRYPTO_malloc(int num, const char *file, int line);
const char *ERR_func_error_string(long e);
int SSL_CTX_use_PrivateKey(void *ctx, void *pkey);
int SSL_use_PrivateKey_file(void *ssl, const char *file, int type);
int SSL_CTX_use_certificate(void *ctx, void *x);
int SSL_state(void *ssl);

void ERR_load_SSL_strings(void);
void ERR_load_crypto_strings(void);
void ERR_free_strings(void);
int SSL_get_error(void *ssl, int ret);

void *BIO_new(void *type);
int BIO_free(void *a);
long BIO_ctrl(void *bp, int cmd = bio_ctrl_cmd, long larg, void*parg);
int BIO_read(void *b, void *buf, int len);
int BIO_gets(void *b, char *buf, int size);
int BIO_write(void *b, const void *buf, int len);
int BIO_puts(void *b, const char *buf);
int BIO_printf(void *bio, const char *format, void *args); 
unsigned long BIO_number_written(void *bio);
unsigned long BIO_number_read(void *bio);
void *BIO_find_type(void *b, int bio_type = bio_type);
int BIO_dump_indent (void *bp, const char *s, int len, int indent);
int BIO_dump_indent_fp (void *fp, const char *s, int len, int indent);
void *SSL_get_rbio(void *ssl);
void *SSL_get_wbio(void *ssl);
void *PEM_read_bio_PrivateKey(void *bp, void **x, void *cb, void *u);
void *PEM_read_bio_X509_AUX(void *bp, void **x, void *cb, void *u);

void *EVP_PKEY_new(void);

int X509_check_private_key(void *x, void *k);
void X509_free(void *a);
const char *X509_get_default_cert_area(void);
int SSL_use_certificate_file(void *ssl, const char *file, int type);
int X509_verify_cert(void *ctx);
int X509_load_cert_file(void *ctx, const char *file, int type);
int X509_STORE_add_cert(void *ctx, void *x);
const char* X509_get_default_cert_file(void);
const char* X509_get_default_cert_file_env(void);
int X509_load_cert_crl_file(void *ctx, const char *file, int type);
const char *X509_get_default_cert_dir(void);
const char *X509_get_default_cert_dir_env(void);
const char *X509_verify_cert_error_string(long n);
int X509_STORE_CTX_get_error(void *ctx);
int X509_STORE_CTX_get_error_depth(void *ctx);
void *X509_STORE_CTX_get_current_cert(void *ctx);
int X509_STORE_load_locations(void *store, const char *file, const char *dirs);
long ERR_get_error(void);

void *SSL_get_peer_certificate(void *ssl);

int NCONF_load(void *conf, const char *file, long *eline);

size_t BUF_strlcpy(void *dst, const char *src, size_t size);

void *lh_insert(void *lh, void *data);

//long bn_mul_add_words(void *rp, void *ap, int num, long w);
